-- MySQL Script generated by MySQL Workbench
-- Fri May  2 17:18:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema protofrutilara
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema protofrutilara
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `protofrutilara` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `protofrutilara` ;

-- -----------------------------------------------------
-- Table `protofrutilara`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `protofrutilara`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `codigo_categoria` VARCHAR(40) NOT NULL,
  `descripcion_categoria` VARCHAR(45) NOT NULL,
  `estado_registro` TINYINT NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `protofrutilara`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `protofrutilara`.`cliente` (
  `cedula` VARCHAR(45) NOT NULL,
  `nombre_apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `estado_registro` TINYINT NOT NULL,
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `protofrutilara`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `protofrutilara`.`empleados` (
  `cedula` VARCHAR(45) NOT NULL,
  `nombre_apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `fechaNacimiento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `protofrutilara`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `protofrutilara`.`proveedores` (
  `rif` VARCHAR(45) NOT NULL,
  `documento` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `estado_registro` TINYINT NOT NULL,
  PRIMARY KEY (`rif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `protofrutilara`.`nota_entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `protofrutilara`.`nota_entrada` (
  `id_entrada` INT NOT NULL AUTO_INCREMENT,
  `rif_proveedores` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id_entrada`),
  INDEX `fk_entrada_proveedores1_idx` (`rif_proveedores` ASC),
  CONSTRAINT `fk_entrada_proveedores1`
    FOREIGN KEY (`rif_proveedores`)
    REFERENCES `protofrutilara`.`proveedores` (`rif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `protofrutilara`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `protofrutilara`.`marca` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `codigo_marca` VARCHAR(45) NOT NULL,
  `descripcion_marca` VARCHAR(45) NOT NULL,
  `estado_registro` TINYINT NOT NULL,
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `protofrutilara`.`unidades_de_medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `protofrutilara`.`unidades_de_medida` (
  `id_medidas` INT NOT NULL AUTO_INCREMENT,
  `codigo_medida` VARCHAR(40) NOT NULL,
  `unidadMedNormal` VARCHAR(45) NOT NULL,
  `unidadMedAlt` VARCHAR(45) NOT NULL,
  `estado_registro` TINYINT NOT NULL,
  PRIMARY KEY (`id_medidas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `protofrutilara`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `protofrutilara`.`producto` (
  `codigo` VARCHAR(45) NOT NULL,
  `id_modelo` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  `marca_id_marca` INT NOT NULL,
  `unidades_de_medida_id_medidas` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `cantidad_total` VARCHAR(45) NOT NULL,
  `minimo` VARCHAR(45) NOT NULL,
  `maximo` VARCHAR(45) NOT NULL,
  `nacionalidad_producto` VARCHAR(45) NOT NULL,
  `estado_registro` TINYINT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_producto_categoria1_idx` (`id_categoria` ASC),
  INDEX `fk_producto_unidades_de_medida1_idx` (`unidades_de_medida_id_medidas` ASC),
  INDEX `fk_producto_marca1_idx` (`marca_id_marca` ASC),
  CONSTRAINT `fk_producto_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `protofrutilara`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_unidades_de_medida1`
    FOREIGN KEY (`unidades_de_medida_id_medidas`)
    REFERENCES `protofrutilara`.`unidades_de_medida` (`id_medidas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_marca1`
    FOREIGN KEY (`marca_id_marca`)
    REFERENCES `protofrutilara`.`marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `protofrutilara`.`prefacturacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `protofrutilara`.`prefacturacion` (
  `id_salida` INT NOT NULL AUTO_INCREMENT,
  `cedula_empleado` VARCHAR(50) NOT NULL,
  `cedula_cliente` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id_salida`),
  INDEX `fk_salida_cliente1_idx` (`cedula_empleado` ASC),
  INDEX `fk_salida_empleados1_idx` (`cedula_cliente` ASC),
  CONSTRAINT `fk_salida_cliente1`
    FOREIGN KEY (`cedula_empleado`)
    REFERENCES `protofrutilara`.`cliente` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_salida_empleados1`
    FOREIGN KEY (`cedula_cliente`)
    REFERENCES `protofrutilara`.`empleados` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `protofrutilara`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `protofrutilara`.`usuario` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuario` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `protofrutilara`.`detalle_entrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `protofrutilara`.`detalle_entrada` (
  `id_detalle_entrada` INT NOT NULL,
  `id_entrada` INT NOT NULL,
  `codigo_producto` VARCHAR(45) NOT NULL,
  `Cantidad_producto` VARCHAR(45) NOT NULL,
  `precio_producto` VARCHAR(45) NOT NULL,
  `tasa_precio` VARCHAR(45) NOT NULL,
  `metodo_pago` VARCHAR(45) NOT NULL,
  INDEX `fk_entrada_has_producto_producto1_idx` (`codigo_producto` ASC),
  INDEX `fk_entrada_has_producto_entrada_idx` (`id_entrada` ASC),
  PRIMARY KEY (`id_detalle_entrada`),
  CONSTRAINT `fk_entrada_has_producto_entrada`
    FOREIGN KEY (`id_entrada`)
    REFERENCES `protofrutilara`.`nota_entrada` (`id_entrada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrada_has_producto_producto1`
    FOREIGN KEY (`codigo_producto`)
    REFERENCES `protofrutilara`.`producto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `protofrutilara`.`detalle_salida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `protofrutilara`.`detalle_salida` (
  `id_detalle_salida` INT NOT NULL,
  `codigo_producto` VARCHAR(45) NOT NULL,
  `id_salida` INT NOT NULL,
  `Cantidad_producto` VARCHAR(45) NOT NULL,
  `precio_producto` VARCHAR(45) NOT NULL,
  `tasa_precio` VARCHAR(45) NOT NULL,
  `metodo_pago` VARCHAR(45) NOT NULL,
  INDEX `fk_producto_has_salida_salida1_idx` (`id_salida` ASC),
  INDEX `fk_producto_has_salida_producto1_idx` (`codigo_producto` ASC),
  PRIMARY KEY (`id_detalle_salida`),
  CONSTRAINT `fk_producto_has_salida_producto1`
    FOREIGN KEY (`codigo_producto`)
    REFERENCES `protofrutilara`.`producto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_has_salida_salida1`
    FOREIGN KEY (`id_salida`)
    REFERENCES `protofrutilara`.`prefacturacion` (`id_salida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `protofrutilara`.`pago_empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `protofrutilara`.`pago_empleados` (
  `id_pago_empleados` INT NOT NULL,
  `fecha_pago` DATE NOT NULL,
  `empleados_cedula` VARCHAR(45) NOT NULL,
  `pago_empleados` VARCHAR(45) NOT NULL,
  `estado_registro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pago_empleados`),
  INDEX `fk_pago_empleados_empleados1_idx` (`empleados_cedula` ASC),
  CONSTRAINT `fk_pago_empleados_empleados1`
    FOREIGN KEY (`empleados_cedula`)
    REFERENCES `protofrutilara`.`empleados` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `protofrutilara`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `protofrutilara`.`servicios` (
  `codigo_servicio` INT NOT NULL,
  `descripcion_servicio` VARCHAR(45) NOT NULL,
  `estado_registro` TINYINT NOT NULL,
  PRIMARY KEY (`codigo_servicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `protofrutilara`.`pago_servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `protofrutilara`.`pago_servicios` (
  `id_servicios` INT NOT NULL,
  `servicios_codigo_servicio` INT NOT NULL,
  `costo` VARCHAR(45) NOT NULL,
  `pago` VARCHAR(45) NOT NULL,
  `fecha_pago_servicio` DATE NOT NULL,
  `estado_registro` TINYINT NOT NULL,
  PRIMARY KEY (`id_servicios`),
  INDEX `fk_pago_servicios_servicios1_idx` (`servicios_codigo_servicio` ASC),
  CONSTRAINT `fk_pago_servicios_servicios1`
    FOREIGN KEY (`servicios_codigo_servicio`)
    REFERENCES `protofrutilara`.`servicios` (`codigo_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `protofrutilara`.`conciliacion_bancaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `protofrutilara`.`conciliacion_bancaria` (
  `id_bancaria` INT NOT NULL,
  `documento` VARCHAR(45) NOT NULL,
  `gasto_banco` VARCHAR(45) NOT NULL,
  `total_banco` VARCHAR(45) NOT NULL,
  `comparativa` VARCHAR(45) NOT NULL,
  `filtrar_fecha` DATE NOT NULL,
  PRIMARY KEY (`id_bancaria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `protofrutilara`.`gastos_generales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `protofrutilara`.`gastos_generales` (
  `id_gastos_generales` INT NOT NULL,
  `nota_entrada_datos_entrada` INT NOT NULL,
  `prefacturacion_datos_salida` INT NOT NULL,
  `pago_servicios_datos_servicios` INT NOT NULL,
  `pago_empleados_datos_pago_empleados` INT NOT NULL,
  PRIMARY KEY (`id_gastos_generales`),
  INDEX `fk_gastos_generales_nota_entrada1_idx` (`nota_entrada_datos_entrada` ASC),
  INDEX `fk_gastos_generales_prefacturacion1_idx` (`prefacturacion_datos_salida` ASC),
  INDEX `fk_gastos_generales_pago_servicios1_idx` (`pago_servicios_datos_servicios` ASC),
  INDEX `fk_gastos_generales_pago_empleados1_idx` (`pago_empleados_datos_pago_empleados` ASC),
  CONSTRAINT `fk_gastos_generales_nota_entrada1`
    FOREIGN KEY (`nota_entrada_datos_entrada`)
    REFERENCES `protofrutilara`.`nota_entrada` (`id_entrada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gastos_generales_prefacturacion1`
    FOREIGN KEY (`prefacturacion_datos_salida`)
    REFERENCES `protofrutilara`.`prefacturacion` (`id_salida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gastos_generales_pago_servicios1`
    FOREIGN KEY (`pago_servicios_datos_servicios`)
    REFERENCES `protofrutilara`.`pago_servicios` (`id_servicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gastos_generales_pago_empleados1`
    FOREIGN KEY (`pago_empleados_datos_pago_empleados`)
    REFERENCES `protofrutilara`.`pago_empleados` (`id_pago_empleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `protofrutilara`.`gastos_generales_has_conciliacion_bancaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `protofrutilara`.`gastos_generales_has_conciliacion_bancaria` (
  `gastos_generales_has_conciliacion_bancaria_id` INT NOT NULL,
  `gastos_generales_id_gastos_generales` INT NOT NULL,
  `conciliacion_bancaria_id_bancaria` INT NOT NULL,
  INDEX `fk_gastos_generales_has_conciliacion_bancaria_conciliacion__idx` (`conciliacion_bancaria_id_bancaria` ASC),
  INDEX `fk_gastos_generales_has_conciliacion_bancaria_gastos_genera_idx` (`gastos_generales_id_gastos_generales` ASC),
  PRIMARY KEY (`gastos_generales_has_conciliacion_bancaria_id`),
  CONSTRAINT `fk_gastos_generales_has_conciliacion_bancaria_gastos_generales1`
    FOREIGN KEY (`gastos_generales_id_gastos_generales`)
    REFERENCES `protofrutilara`.`gastos_generales` (`id_gastos_generales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gastos_generales_has_conciliacion_bancaria_conciliacion_ba1`
    FOREIGN KEY (`conciliacion_bancaria_id_bancaria`)
    REFERENCES `protofrutilara`.`conciliacion_bancaria` (`id_bancaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
